apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wogdb-pv-claim
  labels:
    app: wogdb
spec:
  sorageClassName: adisk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbSize }}